const DEFAULT_MAX_PRICE = 50000;
const DEFAULT_MIN_PRICE = 0;
const DEFAULT_MAX_REVIEWS = 10;
const DEFAULT_CALENDAR_MONTHS = 0;
const DEFAULT_LIMIT_POINTS = 1000;
const DEFAULT_TIMEOUT_MILLISECONDS = 60000;
const HISTOGRAM_ITEMS_COUNT = 10;
const MIN_LIMIT = 20;
const MAX_LIMIT = 50;
const MAX_CONCURRENCY = 50;
const HANDLE_REQUEST_TIMEOUT_SECS = 180;
const DATE_FORMAT = 'YYYY-MM-DD';
const DISTANCE_METERS = 1000;
const URL_WITH_ROOMS_REGEX = /airbnb\.(.)+\/rooms/g;
const MAX_KEY_LENGTH = 256;

module.exports = {
    MAX_LIMIT,
    MAX_CONCURRENCY,
    DEFAULT_MAX_PRICE,
    DEFAULT_MIN_PRICE,
    DEFAULT_MAX_REVIEWS,
    DEFAULT_CALENDAR_MONTHS,
    DEFAULT_LIMIT_POINTS,
    DEFAULT_TIMEOUT_MILLISECONDS,
    HANDLE_REQUEST_TIMEOUT_SECS,
    HISTOGRAM_ITEMS_COUNT,
    DATE_FORMAT,
    MIN_LIMIT,
    DISTANCE_METERS,
    URL_WITH_ROOMS_REGEX,
    MAX_KEY_LENGTH,
};
