const DEFAULT_MAX_PRICE = 50000;
const DEFAULT_MIN_PRICE = 0;
const HISTOGRAM_ITEMS_COUNT = 10;
const MIN_LIMIT = 20;
const MAX_LIMIT = 50;
const DATE_FORMAT = 'YYYY-MM-DD';
const DISTANCE_METERS = 1000;

module.exports = {
    MAX_LIMIT,
    DEFAULT_MAX_PRICE,
    DEFAULT_MIN_PRICE,
    HISTOGRAM_ITEMS_COUNT,
    DATE_FORMAT,
    MIN_LIMIT,
    DISTANCE_METERS,
};
